### ISSUE TITLE
Connect Withdraw button

### ISSUE THREAD

**Issue by gustavoguimaraes** [PoolX-DutchX/poolx-www#21]
At the moment, withdraw button does nothing, connect it to the buyAndCollect function in the smart contract

**Comment by gorgos** [comment]
`buyAndCollect` should be inside #22, for the withdraw button it needs to be `claimFunds`.

**Comment by gustavoguimaraes** [comment]
@gorgos This is done, correct?

**Comment by gorgos** [comment]
yes
