### ISSUE TITLE
Show To User That Collect needs to happen 6 + hours pool is finalized

### ISSUE THREAD

**Issue by gustavoguimaraes** [PoolX-DutchX/poolx-www#22]
Once #21 is resolved, a modal/dialog needs to show to inform user that collection of pool proceeds happens 6 hours after pool is finalized.

**Comment by gorgos** [comment]
And add a `buyAndCollect` button.

**Comment by gorgos** [comment]
Message explaining posting buy order needs to be manually entered still missing.

**Comment by gustavoguimaraes** [comment]
> Message explaining posting buy order needs to be manually entered still missing.

Not sure if I follow. Do you mean a modal exactly how it happens now when a user creates a pool or contributes to a pool

**Comment by gorgos** [comment]
Modal or inside ViewPool. Theres no explanation to the user yet. Needs to be a longer text explaining the whole process.
